matrix:
  include:
    - language: node_js
      sudo: required
      dist: trusty
      node_js: 8.3
      script:
      - npm run lint
      - npm run test-unit
      before_install:
      - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_39958aaf0600_key
        -iv $encrypted_39958aaf0600_iv -in auth.js.enc -out tests/resources/auth.js -d ||
        true'
      - sudo wget https://openwhisk.ng.bluemix.net/cli/go/download/linux/386/wsk -P /usr/local/bin/
      - sudo chmod 711 /usr/local/bin/wsk
      - export PATH=$PATH:"/usr/local/bin/wsk"
      install:
      - npm install
      - 'if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then cd appscan; make asoc-tool; cd ../; fi'
      before_script:
      - 'if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then chmod a+x ./appscan/ASOC.sh; fi'
      script:
      - 'if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then ./appscan/ASOC.sh; fi'
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx travis-deploy-once "npx semantic-release"
    - language: scala
      scala:
        - 2.11.11
      services:
        - docker
      env:
        global:
          - TERM=dumb
      notifications:
        email: false
      install: true
      before_install:
      - "./tools/travis/setup.sh"
      script:
      - "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/deploy_openwhisk_sdk.sh
        && ./tools/travis/test.sh"
      # - "./tools/travis/deploy.sh"
